version: '3.8'  # Specify docker-compose version

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest  # Use the official MLflow Docker image
    container_name: cords-mlflow
    ports:
      - 4000:4000  # Expose MLflow UI on port 5000
    volumes:
      - ./mlruns:/mlruns  # Mount local directory to store MLflow artifacts and metadatas
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:4000  # Set the tracking URI to the running container
      - MLFLOW_S3_ENDPOINT_URL=  # Optional: If using S3 storage, provide the endpoint URL
      - AWS_ACCESS_KEY_ID=  # Optional: AWS access key (if using S3)
      - AWS_SECRET_ACCESS_KEY=  # Optional: AWS secret key (if using S3)

    command: mlflow server --host="0.0.0.0" --port="4000"
    networks:
      - local

  cords-resource-manager:
    image: tharindupr/cords-docker-images:resource_manager
    container_name: resource_manager
    ports:
      - "5000:5000"
    volumes:
      - ./policies/:/app/policies
    environment:
      FLASK_APP: app.py
      # Dynaconf environment variables from settings.toml
      DYNACONF_DEBUG: "true"
      DYNACONF_SECRET_KEY: "change_this_in_prod"
      DYNACONF_HOST: "0.0.0.0"
      DYNACONF_PORT: "4000"
      DYNACONF_ENV: "development"
      # True Connector configuration
      DYNACONF_TRUE_CONNECTOR_TEMPLATE: "data/true_connector_resource.json"
      DYNACONF_TRUE_CONNECTOR_PROXY_URL: "https://localhost:8184/proxy"
      DYNACONF_TRUE_CONNECTOR_SD_URL: "https://172.17.0.1:8090"
      DYNACONF_TRUE_CONNECTOR_BROKER_URL: "https://broker-reverseproxy/infrastructure"
      DYNACONF_TRUE_CONNECTOR_API_USER_NAME: "apiUser"
      DYNACONF_TRUE_CONNECTOR_API_PASSWORD: "password"
      # MLflow configuration
      DYNACONF_MLFLOW_URI: "http://127.0.0.1:3000"
      DYNACONF_MLFLOW_ARTIFACT_PATH: "/vagrant/mlflow/mlartifacts"
      # Orchestrator configuration
      DYNACONF_ORCHESTRATOR_URI: "http://127.0.0.1:4840"
    networks:
      - local
      
networks:
  local:
    driver: bridge


  